version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8080:8080"
    # For local development you can place real credentials in a .env file (ignored by git).
    # Compose will automatically load variables from .env and substitute below.
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST:-example-host}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-example-user}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-example-pass}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-example-db}"
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./uploads:/var/www/html/wp-content/uploads
    networks:
      - resume_network

volumes:
  wordpress_data:

networks:
  resume_network:
    driver: bridge