version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: svc.sel4.cloudtype.app:30333
      WORDPRESS_DB_USER: blog
      WORDPRESS_DB_PASSWORD: 1q2w3e
      WORDPRESS_DB_NAME: blog
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./uploads:/var/www/html/wp-content/uploads
    networks:
      - resume_network

volumes:
  wordpress_data:

networks:
  resume_network:
    driver: bridge